import { Article } from './types';

export const chemistryMeetsPerception: Article = {
    id: "chemistry-meets-perception",
    title: "Does Mint Have a Shape🔶? The Geometric Mystery of Smell",
    excerpt: "What makes mint smell minty or musk smell musky? A 1960s theory proposed that it’s all about molecular shape — and it shaped how we thought about smell for decades.",
    category: "Fascinating History",
    readingTime: 3,
    publishDate: "2025-06-05",
    tags: ["Olfaction", "Receptor Theory", "History"],
    author: "Dr. Liam Lee",
    images: {
        "lockandkey": {
            url: "/images/Lockandkey.png",
            caption: "Lock and key model of molecular fit.",
            source: "Image generated by Gemini Banana Pro"
        },
        "primaryodors": {
            url: "/images/Primary Odors.png",
            caption: "Seven primary odors.",
            source: "Image generated by Gemini Banana Pro"
        }
    },
    content: `
**Can your nose tell the difference between a rose and a rotten egg by molecule shape alone? In the 1960s, one scientist thought so — and the world listened.**

## Meet John Amoore

In **1963**, British chemist **John Amoore** proposed the now-famous **stereochemical theory of olfaction**[1]. His idea? Smell molecules fit into receptors like keys into locks. Different shapes triggered different receptors, and different combinations of receptors created different odor perceptions.

:::image(lockandkey)

## The Primary Odors

Amoore even suggested a list of **“primary odors,”** much like the primary colors of light (red, green, blue). These included:

- **Camphoraceous** (think sharp, medicinal scent)
- **Musky**
- **Floral**
- **Pepperminty**
- **Ethereal** (like cleaning fluid)
- **Pungent**
- **Putrid**

According to him, every odor we perceive was a mix of these building blocks, detected through molecular fit.

:::image(primaryodors)

## A Theory With Teeth

Why did this theory catch fire?

1. **It matched how medicines work**. Scientists already knew that drugs rely on shape to unlock specific effects in the body, so it made sense for smell to do the same.

2. **It explained specific anosmias** — cases where people couldn’t smell one specific odor (like musky or cheese-like odors) but could smell everything else. Maybe they were missing a receptor for that shape.

## Not the Whole Picture — But a Key Chapter

While later discoveries would show that the story of smell is more complex — involving hundreds of odorant receptors and combinatorial coding — Amoore’s work set the stage. He gave scientists a **testable hypothesis** and a conceptual framework to work from.

## Why This Still Matters, Even Today

Amoore’s theory fueled a generation of olfactory science. It also laid the foundation for the **1991 discovery** of the **olfactory receptor gene family** — which proved that yes, we do have hundreds of smell-specific receptors, and yes, they respond (at least in part) to shape.

That makes this 1963 paper one of the most influential — even if no longer the full story.

So next time you smell peppermint, remember: it all started with the idea that your nose reads molecular geometry.
  `,
    sources: [
        {
            title: "Stereochemical Theory of Olfaction",
            url: "https://doi.org/10.1038/199912b0"
        }
    ]
};
